### ISSUE TITLE
Can't mount SD card and display at the same time (SPI host already in use)

### ISSUE THREAD

**Issue by ryanfobel** [sci-bots/m5-lvgl#1]
# Summary

The [m5stack][1] development boards share the same SPI bus between their display (ili9341) and SD card interface. This leads to an SPI bus conflict when trying to use the display and SD card
simultaneously, as previously reported by [others][2] using the same display.

# Steps to reproduce

The following example `boot.py` demonstrates the problem when interpreted by [this](https://github.com/sci-bots/micropython/releases/tag/v1.11-877-gbf7699eee-m5stack) micropython release:

```python
import machine
import os
import lvgl as lv
import lvesp32
import ili9341

# Mount the SD card (note that this initializes the SPI bus)
os.mount(machine.SDCard(slot=3, sck=18, mosi=23, miso=19, cs=4), '/sd')

# Create display driver
lv.init()
disp = ili9341.ili9341(spihost=1, miso=19, mosi=23, clk=18, cs=14, dc=27,
                       rst=33, backlight=32, mhz=25)

```

Here's the error message:

```python
E (410) spi: SPI2 already claimed by spi master.
E (410) spi_master: spi_bus_initialize(242): host already in use
Traceback (most recent call last):
  File "boot.py", line 12, in <module>
  File "ili9341.py", line 108, in __init__
  File "ili9341.py", line 264, in init
  File "ili9341.py", line 181, in disp_spi_init
RuntimeError: Failed initializing SPI bus
```

A similar error occurs if the display is initialized before trying to mount the SD card.

[1]: https://m5stack.com/collections/m5-core
[2]: https://hackaday.io/project/162059-street-sense/log/170296-farewell-loboris-hello-littlevgl

**Comment by ryanfobel** [comment]
Note that @miketeachman came up with a nice [workaround](https://github.com/miketeachman/lv_binding_micropython/commit/a166c3c33bf39638643bb630edb80ffbbf169885#diff-7ab562f4efe79d126fde9181d13712ca) for his project that uses an ESP32 and ili9341 display (though not an m5stack). Inspired by his work, [this commit](https://github.com/sci-bots/lv_binding_micropython/commit/e0f4a56bc834599237cb8c44ffcad3fbfd0337db) adds 2 custom build flags that enable compiling the ILI9341 C module so that the m5stack display can be properly configured and added to a pre-initialized SPI bus:

* `LV_M5STACK`: When defined, adjust the screen rotation and color mapping to match the M5Stack modules.
* `LV_ILI9341_SHARE_SPI_BUS`: When defined, assume that the SPI bus has already been initialized and add the display to the existing bus. Note that this also sets the display to use Full-Duplex mode.

To build it, you'll need to uncomment a couple of lines in `/ports/esp32/mpconfigport.h`, since the C module is no longer included by default since the release of the ili9341 [python hybrid module](https://blog.littlevgl.com/2019-08-05/micropython-pure-display-driver).

```diff
diff --git a/ports/esp32/mpconfigport.h b/ports/esp32/mpconfigport.h
index a958ccc8f..a24a1a070 100644
--- a/ports/esp32/mpconfigport.h
+++ b/ports/esp32/mpconfigport.h
@@ -201,14 +201,14 @@ extern const struct _mp_obj_module_t mp_module_espidf;
 extern const struct _mp_obj_module_t mp_module_lvesp32;
 extern const struct _mp_obj_module_t mp_module_rtch;
 extern const struct _mp_obj_module_t mp_module_lodepng;
-// extern const struct _mp_obj_module_t mp_module_ILI9341;
+extern const struct _mp_obj_module_t mp_module_ILI9341;
 // extern const struct _mp_obj_module_t mp_module_xpt2046;

 #if MICROPY_PY_LVGL
 #define MICROPY_PORT_LVGL_DEF \
     { MP_OBJ_NEW_QSTR(MP_QSTR_lvgl), (mp_obj_t)&mp_module_lvgl }, \
-    { MP_OBJ_NEW_QSTR(MP_QSTR_lvesp32), (mp_obj_t)&mp_module_lvesp32 },
-//    { MP_OBJ_NEW_QSTR(MP_QSTR_ILI9341), (mp_obj_t)&mp_module_ILI9341 },
+    { MP_OBJ_NEW_QSTR(MP_QSTR_lvesp32), (mp_obj_t)&mp_module_lvesp32 }, \
+    { MP_OBJ_NEW_QSTR(MP_QSTR_ILI9341), (mp_obj_t)&mp_module_ILI9341 },
 //    { MP_OBJ_NEW_QSTR(MP_QSTR_xpt2046), (mp_obj_t)&mp_module_xpt2046 },
 #else
 #define MICROPY_PORT_LVGL_DEF
```

Then follow the [standard steps](https://github.com/littlevgl/lv_micropython#for-esp32-port) to compile micropython with LittlevGL bindings, but use the following build flags:

```sh
make -C ports/esp32 LV_CFLAGS="-DLV_COLOR_DEPTH=16 -DLV_COLOR_16_SWAP=1 \
-DLV_ILI9341_SHARE_SPI_BUS -DLV_M5STACK" BOARD=GENERIC PYTHON=python2
```

Or you can download [this](https://github.com/sci-bots/m5-lvgl/files/4201216/lv_micropython-LV_COLOR_DEPTH_16-LV_COLOR_16_SWAP-LV_ILI9341_SHARE_SPI_BUS-LV_M5STACK-v1.11-877-gbf7699eee.bin.zip) pre-compiled firmware. The following `boot.py` provides a minimal example of using an m5stack display and SD card simultaneously:

```python
import machine
import os
import lvgl as lv
import lvesp32
import ILI9341

os.mount(machine.SDCard(slot=3, sck=18, mosi=23, miso=19, cs=4), '/sd')

lv.init()
disp = ILI9341.display(spihost=1, miso=19, mosi=23, clk=18, cs=14, dc=27,
                       rst=33, backlight=32, mhz=25)
disp.init()

disp_buf1 = lv.disp_buf_t()
buf1_1 = bytearray(480*10)
lv.disp_buf_init(disp_buf1,buf1_1, None, len(buf1_1)//4)
disp_drv = lv.disp_drv_t()
lv.disp_drv_init(disp_drv)
disp_drv.buffer = disp_buf1
disp_drv.flush_cb = disp.flush
disp_drv.hor_res = 320
disp_drv.ver_res = 240
disp_drv.rotated = 0
lv.disp_drv_register(disp_drv)

scr = lv.obj()
btn = lv.btn(scr)
btn.align(lv.scr_act(), lv.ALIGN.CENTER, 0, 0)
label = lv.label(btn)
label.set_text("Button")
lv.scr_load(scr)

print(os.listdir('/sd'))
```

**Comment by GC-RnD** [comment]
Made edits to **mpconfigport.h**
started build with...
```
make -C ports/esp32 LV_CFLAGS="-DLV_COLOR_DEPTH=16 -DLV_COLOR_16_SWAP=1 \ -DLV_ILI9341_SHARE_SPI_BUS " BOARD=GENERIC PYTHON=python2
```
and got build error..
```
mkdir -p build-GENERIC/bootloader//mnt/c/tpi-dev/IDF4/esp/esp-idf/components/spi_flash/
CC /mnt/c/tpi-dev/IDF4/esp/esp-idf/components/bootloader_support/src/bootloader_clock.c
xtensa-esp32-elf-gcc: error:  -DLV_ILI9341_SHARE_SPI_BUS: No such file or directory
Makefile:977: recipe for target 'build-GENERIC/bootloader//mnt/c/tpi-dev/IDF4/esp/esp-idf/components/bootloader_support/src/bootloader_clock.o' failed
make: *** [build-GENERIC/bootloader//mnt/c/tpi-dev/IDF4/esp/esp-idf/components/bootloader_support/src/bootloader_clock.o] Error 1
make: Leaving directory '/mnt/c/tpi-dev/IDF4/lv_micropython/ports/esp32'
```

related post
https://forum.micropython.org/viewtopic.php?f=18&t=8352&sid=f84883e0f709647d29736932a8c92973

**Comment by GC-RnD** [comment]
My error...
needed to remove "\\"

**Comment by GC-RnD** [comment]
Were you able to get the pure/hybrid ili9341 driver to work?
